### ISSUE TITLE
minecraft mods search command

### ISSUE THREAD

**Issue by krampuszc** [crazygmr101/AnsuraBot#12]
mod search for forge an other mod launchers

**Comment by DavidCuevasPR** [comment]
> mod search for forge an other mod launchers

When you say mod search, I assume it's to search for a command on CurseForge and retrieve the elements and return them to Discord. My question is what format did you have in mind for the return? An embed with important elements from the mod page, a simple link to the page, or another format that wasn't mentioned?

**Comment by krampuszc** [comment]
> > mod search for forge an other mod launchers
> 
> When you say mod search, I assume it's to search for a command on CurseForge and retrieve the elements and return them to Discord. My question is what format did you have in mind for the return? An embed with important elements from the mod page, a simple link to the page, or another format that wasn't mentioned?

embed
