### ISSUE TITLE
twitch alerts 

### ISSUE THREAD

**Issue by itzsturdy** [crazygmr101/AnsuraBot#3]
add a feature that can send alert messages in selected discord server channel when a streamer is live on twitch.
the alert can contain name of channel, custom message, title of stream, stream preview or thumbnail.

**Comment by crazygmr101** [comment]
Pushed a test release in [9d3559b](https://github.com/crazygmr101/AnsuraBot/commit/9d3559be4716d0b7ddf21fd13971e6b30c798bac)

**Comment by crazygmr101** [comment]
Closed by [af432b9](https://github.com/crazygmr101/AnsuraBot/commit/af432b9acefa4fd11a26c93ad5c16323ca68479b)
Feel free to reopen this if needed
